#!/bin/sh
# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# The environment's checks, from the environment's networks. `isoloom test` runs it and reads the PASS/FAIL lines.
passed=0; failed=0
pass() { passed=$((passed+1)); echo "isoloom-check: PASS $1"; }
fail() { failed=$((failed+1)); echo "isoloom-check: FAIL $1: $2"; }
# _http URL -> the status code, 000 when nothing answers (curl, else wget, else bash).
_http() {
  if command -v curl >/dev/null 2>&1; then
    c=$(curl -sk -o /dev/null -m 5 -w '%{http_code}' "$1" 2>/dev/null)
  elif command -v wget >/dev/null 2>&1; then
    c=$(wget -q -S -O /dev/null -T 5 --no-check-certificate "$1" 2>&1 | sed -n 's/^ *HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p' | tail -n 1)
  else
    u=${1#*://}; hp=${u%%/*}; p=/${u#*/}; [ "$u" = "$hp" ] && p=/
    h=${hp%%:*}; port=${hp#*:}; [ "$hp" = "$h" ] && port=80
    c=$(H=$h P=$port U=$p timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P && printf "GET %s HTTP/1.0\r\nHost: %s\r\n\r\n" "$U" "$H" >&3 && read -r l <&3 && echo "$l"' 2>/dev/null | sed -n 's/^HTTP\/[0-9.]* \([0-9][0-9][0-9]\).*/\1/p')
  fi
  echo "${c:-000}"
}
_http_is() { [ "$(_http "$1")" = "$2" ]; }
_http_any() { [ "$(_http "$1")" != 000 ]; }
# _tcp HOST PORT -> 0 when it connects (nc, else bash).
_tcp() {
  if command -v nc >/dev/null 2>&1; then nc -z -w 5 "$1" "$2" >/dev/null 2>&1
  else H=$1 P=$2 timeout 5 bash -c 'exec 3<>/dev/tcp/$H/$P' >/dev/null 2>&1
  fi
}
# _exec COMMAND TEXT -> 0 when the command succeeds and its output contains TEXT (if any).
_exec() { out=$(sh -c "$1" 2>&1) && { [ -z "$2" ] || printf '%s\n' "$out" | grep -qF -- "$2"; }; }
# _retry SECONDS COMMAND... -> keeps trying every 2s until it passes or the time is up.
_retry() { _end=$(( $(date +%s) + $1 )); shift; while ! "$@"; do [ "$(date +%s)" -lt "$_end" ] || return 1; sleep 2; done; }

if _retry 180 _http_any 'http://www/'; then pass 'Mutillidae answers'; else fail 'Mutillidae answers' "nothing answers at http://www/"; fi

if _retry 120 _http_is 'http://www/index.php?page=home.php' 200; then pass 'the database is built (the home page no longer redirects to the setup page)'; else fail 'the database is built (the home page no longer redirects to the setup page)' "expected HTTP 200 from http://www/index.php?page=home.php, got $(_http 'http://www/index.php?page=home.php')"; fi

echo '== checks/ldap-lookup.sh'
if _retry 120 sh -c 'cd /isoloom/project && sh checks/ldap-lookup.sh'; then pass 'the LDAP conference room lookup finds a room (the directory is loaded)'; else fail 'the LDAP conference room lookup finds a room (the directory is loaded)' "checks/ldap-lookup.sh exited non-zero"; fi

if _retry 120 _http_is 'http://database-admin/' 200; then pass 'phpMyAdmin answers'; else fail 'phpMyAdmin answers' "expected HTTP 200 from http://database-admin/, got $(_http 'http://database-admin/')"; fi

if _retry 120 _http_is 'http://directory-admin/' 200; then pass 'phpLDAPadmin answers'; else fail 'phpLDAPadmin answers' "expected HTTP 200 from http://directory-admin/, got $(_http 'http://directory-admin/')"; fi

echo "isoloom-check: END $passed passed, $failed failed"
[ "$failed" -eq 0 ]
